name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: [stable, beta, nightly]
        include:
          - build: stable
            rust: stable
          - build: beta
            rust: beta
          - build: nightly
            rust: nightly

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust (rustup)
        run: rustup update ${{ matrix.rust }} --no-self-update && rustup default ${{ matrix.rust }}
        shell: bash
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
